// <auto-generated />
using System;
using KeyhookBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KeyhookBooking.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("KeyhookBooking.Models.Availability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DaysOfWeek")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Availabilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DaysOfWeek = "1;5",
                            EndTime = "12:00",
                            IsDeleted = false,
                            ManagerId = 3,
                            SelectedDate = "",
                            StartTime = "10:00",
                            TimeZone = "Pacific/Auckland"
                        },
                        new
                        {
                            Id = 2,
                            DaysOfWeek = "3",
                            EndTime = "16:00",
                            IsDeleted = false,
                            ManagerId = 4,
                            SelectedDate = "",
                            StartTime = "14:00",
                            TimeZone = "Pacific/Auckland"
                        },
                        new
                        {
                            Id = 3,
                            DaysOfWeek = "5",
                            EndTime = "14:00",
                            IsDeleted = false,
                            ManagerId = 3,
                            SelectedDate = "",
                            StartTime = "13:00",
                            TimeZone = "Pacific/Auckland"
                        });
                });

            modelBuilder.Entity("KeyhookBooking.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SlotId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("SlotId", "BookDate")
                        .IsUnique()
                        .HasFilter("[Status] = 'Active'");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("KeyhookBooking.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alice Tenant",
                            Role = "Tenant"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bob Tenant",
                            Role = "Tenant"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Manager Mike",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Manager Jane",
                            Role = "Manager"
                        });
                });

            modelBuilder.Entity("KeyhookBooking.Models.Availability", b =>
                {
                    b.HasOne("KeyhookBooking.Models.User", "Manager")
                        .WithMany("Availabilities")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("KeyhookBooking.Models.Booking", b =>
                {
                    b.HasOne("KeyhookBooking.Models.Availability", "Slot")
                        .WithMany("Bookings")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeyhookBooking.Models.User", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Slot");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KeyhookBooking.Models.Availability", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("KeyhookBooking.Models.User", b =>
                {
                    b.Navigation("Availabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
